### ISSUE TITLE
Unable to request certificate in NC30

### ISSUE THREAD

**Issue by nsauter** [strukturag/nextcloud-certificate24#441]
Hello!

I downloaded Certificate24 for my new NC30 Installation and configured Certificate24 Settings in the Admin Page. Validation of settings is valid when checked. But if i try to request a signature it wont work. Gui just tells me "Fehler beim Anfragen der Signatur.".

Nextcloud Log has the following error:
`{"reqId":"AKMYp4ecJWAB1c91difg","level":3,"time":"2024-10-08T09:13:56+00:00","remoteAddr":"80.154.94.6","user":"Administrator","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/certificate24/api/v1/share","message":"Too few arguments to function OC\\Template\\Base::__construct(), 4 passed in /var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php on line 52 and exactly 5 expected in file '/var/www/nextcloud/lib/private/Template/Base.php' line 30","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","version":"30.0.0.14","exception":{"Exception":"Exception","Message":"Too few arguments to function OC\\Template\\Base::__construct(), 4 passed in /var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php on line 52 and exactly 5 expected in file '/var/www/nextcloud/lib/private/Template/Base.php' line 30","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":43,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":7,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":146,"Previous":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OC\\Template\\Base::__construct(), 4 passed in /var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php on line 52 and exactly 5 expected","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php","line":52,"function":"__construct","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/apps/certificate24/lib/Mails.php","line":75,"function":"__construct","class":"OCA\\Certificate24\\TranslatedTemplate","type":"->"},{"file":"/var/www/nextcloud/apps/certificate24/lib/Mails.php","line":158,"function":"renderTemplate","class":"OCA\\Certificate24\\Mails","type":"->"},{"file":"/var/www/nextcloud/apps/certificate24/lib/Controller/ApiController.php","line":371,"function":"sendRequestMail","class":"OCA\\Certificate24\\Mails","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"shareFile","class":"OCA\\Certificate24\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":43,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":7,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Template/Base.php","Line":30},"message":"Too few arguments to function OC\\Template\\Base::__construct(), 4 passed in /var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php on line 52 and exactly 5 expected in file '/var/www/nextcloud/lib/private/Template/Base.php' line 30","exception":{},"CustomMessage":"Too few arguments to function OC\\Template\\Base::__construct(), 4 passed in /var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php on line 52 and exactly 5 expected in file '/var/www/nextcloud/lib/private/Template/Base.php' line 30"}}`

**Comment by nsauter** [comment]
I managed to get it Working. Seems like public function __construct($template, $requestToken, $l10n, $theme, $cspNonce) 
 in /var/www/nextcloud/lib/private/Template/Base.php expects a nonce, which parent::__construct($template, $requestToken, $l10n, $themeDefaults); in /var/www/nextcloud/apps/certificate24/lib/TranslatedTemplate.php wont deliver. Simply adding a random nonce fixed the issue. Do you accept Pull Request if i fix this in the code?

**Comment by fancycode** [comment]
Hope you didn't start working on this yet, it will be fixed as part of #447.
